
http {
	server {
		# listen 443;
		# listen 555;
		# listen http;
		# listen https;
		# listen 1.1.1.1:8080;
		# listen 0.0.0.0:8080;
		# listen localhost:8080;
		# listen 50111;
		listen 5001;
		listen 5002;
		listen 5003;


		client_max_body_size 2147483K;
	}
}



# 18446744073709551615 max body size

# wefe


# ef