

# --- MAIN CONTEXT (Outside http) ---
# user nginx;
# worker_processes auto;
# error_log /var/log/nginx/error.log notice;
# pid /var/run/nginx.pid;

# --- EVENTS CONTEXT (Outside http) ---
# events {
#     worker_connections 1024;
# }

# --- STREAM CONTEXT (Outside http) ---
# stream {
#     upstream database {
#         # Remove :// and add the backend port (e.g., 3306)
#         server example.com:3306; 
#     }

#     server {
#         listen 3306;
#         proxy_pass database;
#     }
# }


http {

# root ./html/static;

	    # error_page 500 /errors/500.html; #todo:

	# client_header_buffer_size 1k; #todo: ?
   	# client_timeout 50s;
	client_max_body_size 50M;

	server {listen 0.0.0.0:60111;
	listen 127.0.0.1:60112;}

	server{
		listen 0.0.0.0:60113;
		# server_name anders;
		autoindex off;
root ./html/static;
		index index.html;
		location / {
		# allow_methods GET POST DELETE;
		}
	}

	server{
		listen 0.0.0.0:8081;
		# server_name "exam ple.com"; #todo: ?
		autoindex off; root ./html/static;
		index static_index.html;location / {
		# allow_methods GET POST DELETE;
		}
    }

	server {
		listen 8082;
		autoindex on;
		root ./html/directory;
		location /{autoindex on;}location /wrong/url{return 444;}location /permanently/moved/url {return 301 http://www.example.com/moved/here;}}server {
		# client_header_buffer_size 1k; #todo: ?
	   	# client_timeout 60s;
		client_max_body_size 1M;

		listen 0.0.0.0:8083;
		autoindex on;
		root ./html/;
		location /upload/ {
			root ./html/upload_files;
		    # error_page 500 /errors/500.html; #todo: ?

        	# upload_store /;
			# allow_methods GET POST DELETE;
    	}
		location /errors/ {
			# error_page 404 501     /error.html; #todo: !
			# error_page 502     /error502.html; #todo: !
		}
		location /wrong/url{return 444;}
		location /permanently/moved/url {
			return 301 http://www.example.com/moved/here;
		}
    }

	server {
		listen 127.0.0.1:8084;
		# server_name localhost; #todo: ?
autoindex off;
		root ./html/static;
		index /index.html;

		location "/cgi-php/" {
			# cgi_path /usr/bin/php-cgi;
			root ./html/cgi_files/php;
			# cgi_ext .php;
			index index.php;
		}
	}

	server {
		listen 127.0.0.1:8085;
		# server_name localhost; #todo: ?
		autoindex off;
		root ./html/static;
		index /index.html;

		location /cgi-py/ {
			# cgi_path /usr/bin/python3;
			# cgi_ext .py;
			root ./html/cgi_files/py;
			index /test.py;

		}
		location /cgi-py/eee {
		# cgi_path /usr/bin/python3;
		# cgi_ext .py;
		root ./html/cgi_files/py/efe;
		index /test.pywee;

		}
	}


}

#