http {
    server {
        listen 5001;

        location / {
            root ./www;
            index index.html;
            limit_except GET;
        }

        location /assets {
            root ./www/assets;
            limit_except GET;
        }
    }
}